[package]
name = "orae-http-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["json", "macros", "original-uri"] }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["rt-multi-thread"] }
macros = { path = "../macros" }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter"] }
serde = { version = "1.0.228", features = ["derive"] }
uuid = { version = "1.23.4", features = ["serde", "v4"] }
tracing-error = "0.2.1"
anyhow = "1.0.103"
