[package]
name = "orae-cli"
version = "0.1.0"
edition = "2024"
description = "Opinionated project generator for API-related Rust projects (a 'Spring Initializr' for your own crates)"

[[bin]]
name = "orae"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
inquire = "0.7"
anyhow = "1"
thiserror = "1"
toml_edit = "0.22"
serde = { version = "1.0.229", features = ["derive"] }
itertools = "0.15.0"
